alibaba/flutter-go

lib/views/FirstPage.dart, lib/views/collection_page.dart, lib/views/widgetPage.dart
=> feat:切换tab避免重绘g

lib/common/widget_demo.dart
=> collection

lib/common/provider.dart
判断是否存在已知的cat, widget, collection三张表.
=> refactor(整理数据库初始逻辑, 判断数据库完整性)

lib/main.dart
> 通过包裹一层`SafeArea`
> 格式化了修改过的那块代码
=> 适配首页底部Tabbar在iPhoneX以上机型的UI问题

lib/main.dart
=> refactor:modified icons

ios/Runner.xcodeproj/project.pbxproj, lib/model/collection_general.dart, lib/views/collection_page.dart, lib/views/web_view_page.dart
=> fix:collection bug

lib/views/home.dart
=>  Modfiy:关于手册图标更换

lib/common/widget_demo.dart, lib/views/web_view_page.dart, lib/widgets/components/Menu/CheckedPopupMenuItem/demo.dart, lib/widgets/components/Menu/PopupMenuButton/demo.dart, lib/widgets/components/Menu/PopupMenuDivider/demo.dart, lib/widgets/themes/Material/MaterialColor/demo.dart, pubspec.yaml
=> fix:fluttetToast backHome

ios/Runner.xcodeproj/project.pbxproj, lib/utils/example_code_parser.dart, lib/widgets/components/LIst/AnimatedList/demo.dart, lib/widgets/components/Scroll/CustomScrollView/demo.dart, lib/widgets/elements/Frame/Spacing/SliverPadding/sliverpadding_demo.dart
=> fix:refactor bug

lib/components/list_refresh.dart, lib/components/search_input.dart, lib/widgets/components/Card/Card/demo.dart, lib/widgets/components/Grid/GridTileBar/index.dart, lib/widgets/elements/Form/Button/DropdownButton/demo.dart
=> refactor:按规范修改代码、注释等

lib/widgets/components/Bar/TabBar/index.dart
=> fix:修复TabBar demo

lib/main.dart
展示 WelcomePage 时，showWelcomePage 方法被重复调用了。
=> pref: 移除showWelcomePage的非必要调用

README.md
=> update: 修改错字

LICENSE, README.md, ios/Runner.xcodeproj/project.pbxproj
1.变更许可 
2.Debug: GoogleService-Info.plist 位置问题 导致错误
=> Modfiy：1.变更许可  2.Debug: GoogleService-Info.plist 位置问题 导致错误

lib/views/home.dart
=> add home scaffold

lib/views/first_page/drawer_page.dart, lib/views/home.dart, lib/views/user_page/user_page.dart
=> feat:添加个人中心

lib/views/first_page/drawer_page.dart, lib/views/login_page/login_page.dart
=> bugfix:登录页添加错误提醒

lib/components/disclaimer_msg.dart
bug #330 
修复首页弹出框点击 Checkbox 闪屏的bug；
修复点击「不再自动提示」然后确认，再次点击左上角「免责声明」弹出框内还留有「不再自动提示、知道了」等 Widget的bug
=> bug #330  免责声明的bug

lib/components/widget_demo.dart, lib/views/login_page/login_page.dart
#341 
修复游客模式下查看 widget 点击 home 按钮报错问题
=> bug fix #341

lib/components/home_banner.dart
个人最近也在开发banner 组件，也思路也与flutter-go 组件大体一致，看到组件最后一页过渡很不平滑。滑动很快结束，所以就把自己的优化方法提交上来
=> 优化 HomeBanner 组件最后一页滑动过渡效果

lib/utils/shared_preferences.dart
[TrelloCard/Issue/Story](LINK_TO_STORY)
---
=> SharedPreferences 两个地方同时调用导致_spf为null而取不到值

README-en.md, lib/widgets/components/Navigation/BottomNavigationBar/demo.dart, lib/widgets/components/Navigation/BottomNavigationBar/index.dart
=> 增加 BottomNavigationBar 选中文字大小说明
